---
# tasks file for ansible-role-opentofu

- name: Include OS specific variables.
  ansible.builtin.include_vars: "{{ ansible_system }}.yml"

- name: Install OpenTofu
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "setup-{{ ansible_system }}.yml"
        - "setup-Linux-Unix.yml"
      paths:
        - "tasks"
