---
# tasks file for ansible-role-opentofu

- name: Include OS specific variables.
  ansible.builtin.include_vars: "{{ ansible_system }}.yml"

- name: Linux |Install OpenTofu
  ansible.builtin.include_tasks: "setup-{{ ansible_system }}.yml"
