---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: linux
    image: ${namespace:-diodonfrost}/${image:-ansible-ubuntu:24.04}
    command: ${cmd:-"sleep 999"}
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
