---
- name: Verify
  hosts: all
  tasks:
    - name: Windows | OpenTofu should be functional
      ansible.windows.win_command: tofu --version
      register: opentofu_result

    - name: Windows | Verify commands outputs
      ansible.builtin.assert:
        that:
          - opentofu_result.rc == 0
        success_msg: "All tests passed"
